services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-local-compose
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
