# This docker compose is used by the scripts/fly:deploy.sh script
# APP_DIR_PATH
# PLATFORM
# REGISTRY
# APP_NAME
# TAG
# APP_PORT

services:
  app:
    build:
      # This is CRUCIAL as it sets the working directory for docker compose and dockerfile
      # https://docs.docker.com/reference/compose-file/build/#context
      context: ${APP_DIR_PATH}
      platforms:
        - ${PLATFORM}
      dockerfile: Dockerfile
    image: ${REGISTRY}/${APP_NAME}:${TAG}
    container_name: ${APP_NAME}
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
    ports:
      - "${APP_PORT}:${APP_PORT}"
