services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-local-compose
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
