name: Format, Lint, and Build

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  format-lint-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run formatter
        run: bun format:check

      - name: Run linter
        run: bun lint

      - name: Build application
        env:
          NODE_ENV: production
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/github-actions
          NEXT_PUBLIC_BACKEND_URL: http://localhost:1284
          NEXT_PUBLIC_FRONTEND_URL: http://localhost:3000
          NEXT_PUBLIC_CALLBACK_URL: http://localhost:3000/app
        run: bun run build
